version: '3'

services:
  web:
    image: dev_server
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - BROKER_URL=redis://cache
      - DATABASE_URL=postgres://postgres@db:5432/django_db
    links:
      - redis:cache
      - postgres:db

  worker:
    image: dev_worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/code
    command: python manage.py celery_autoreload
    env_file: .env
    environment:
      - BROKER_URL=redis://cache
      - DATABASE_URL=postgres://postgres@db:5432/django_db
    links:
      - redis:cache
      - postgres:db

  redis:
    image: redis
    expose:
      - 6379

  postgres:
    image: postgres:11
    expose:
      - 5432
    volumes:
      - database_volume:/var/lib/postgresql/data

  webpack:
    image: dev_webpack
    build:
      context: .
      dockerfile: Dockerfile.webpack
    volumes:
      - ./assets:/code/assets
    command: npm run dev

volumes:
  database_volume:
